### ISSUE TITLE
planned projects

### ISSUE THREAD

**Issue by ChillerDragon** [ChillerDragon/github-meta#2]
- [ ] https://github.com/BingeBounty
- [ ] https://github.com/ZillyHuhn/chat
- [ ] https://github.com/scosu/teeworlds/tree/ball0.6.1 tees requested me to port this to 0.7
- [ ] [DELETE THIS REPO](https://github.com/ChillerDragon/github-meta/issues/4)
