### ISSUE TITLE
watch later

### ISSUE THREAD

**Issue by ChillerDragon** [ChillerDragon/github-meta#3]
List of repos that I want to look into. This list replaces my habit of starring repos to mark them as "read later".

- [ ] https://github.com/tillson/git-hound
- [ ] https://github.com/ForrestKnight/open-source-cs
- [ ] https://github.com/mozilla/hubs
- [ ] https://github.com/sc0tfree/mentalist
- [ ] https://github.com/sandsmark/slaq
- [ ] https://github.com/lbryio/lbrytv
- [ ] https://github.com/purism
- [ ] https://github.com/buckket/twtxt
- [ ] https://github.com/aosabook/500lines
- [ ] https://github.com/vvaltchev/tilck
- [ ] https://github.com/zebscripts/AFK-Daily (mobile app automation)
- [ ] https://github.com/k4yt3x/video2x

# security

- [ ] https://github.com/Mebus/cupp
- [ ] https://github.com/FlameOfIgnis/Pwdb-Public
- [ ] https://github.com/mohitkhemchandani/OSCP_BIBLE
- [ ] https://github.com/TH3xACE/SUDO_KILLER

# minecraft

- [x] https://github.com/Earthcomputer/clientcommands
- [x] https://github.com/kami-blue/client
- [ ] https://github.com/ORelio/Minecraft-Console-Client
- [ ] https://github.com/x4e/PaperBin
- [ ] https://github.com/Querz/mcaselector (remove unused chunks from anarchy world?)

# not even github. Why is this here?!

- [ ] https://joev.dev/posts/unprivileged-process-injection-techniques-in-linux
- [ ] https://memorycorruption.net/posts/rce-lua-factorio/
